-- ========================================
-- INITIAL ADMIN USER MIGRATION
-- File: V1__create_initial_admin.sql
-- Run this ONCE during initial deployment
-- ========================================

-- This creates the first admin user for the system
-- In production, change the password immediately after first login

INSERT INTO staff (
    first_name,
    last_name,
    email,
    password,
    phone_number,
    employee_number,
    role,
    hired_at,
    active,
    last_login_at
)
SELECT
    'System',
    'Administrator',
    'admin@albanet.com',
    '$2a$10$YOUR_BCRYPT_HASH_HERE',  -- Generated by PasswordEncoder
    '+355 00 000 0000',
    'EMP-000001',
    'ADMIN',
    CURRENT_TIMESTAMP,
    true,
    NULL
WHERE NOT EXISTS (
    SELECT 1 FROM staff WHERE email = 'admin@albanet.com'
);

-- Verification
SELECT
    'Initial admin created' as status,
    email,
    role,
    active
FROM staff
WHERE email = 'admin@albanet.com';
